version: '3.8'

services:
  product-checker:
    image: ghcr.io/axkng/product-availability-checker:latest
    container_name: product-checker
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json:ro
      - ./logs:/app/logs
    # Uncomment to limit resources
    # deploy:
    #   resources:
    #     limits:
    #       memory: 512M
    #       cpus: '0.5'